version: '3.8'

services:
  cart-service:
    image: truongikpk/bookstore-cart-service:v1.0.0
    container_name: cart-service
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
